// app/terms/page.tsx
import Navigation from '@/components/layout/Navigation'
import Footer from '@/components/layout/Footer'

export default function TermsPage() {
  return (
    <main className="min-h-screen">
      <Navigation />
      <div className="pt-24 sm:pt-28 pb-20 max-w-3xl mx-auto px-4 sm:px-6">
        <h1 className="font-display font-bold text-3xl sm:text-4xl mb-2">Terms of Service</h1>
        <p className="text-text-muted text-sm mb-10">Last updated: March 23, 2026</p>

        <div className="prose-custom space-y-8">
          <section>
            <h2 className="font-display font-semibold text-lg text-accent-cyan mb-3">1. Acceptance of Terms</h2>
            <p className="text-text-secondary text-sm leading-relaxed">
              By accessing or using Peptidrop ("the Platform"), you agree to be bound by these Terms of Service. If you do not agree to all of these terms, do not use the Platform. These terms apply to all visitors, users, and others who access or use the Platform.
            </p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-lg text-accent-cyan mb-3">2. Description of Service</h2>
            <p className="text-text-secondary text-sm leading-relaxed">
              Peptidrop is an AI-powered peptide intelligence platform that provides educational information about peptides, including mechanisms of action, synergy data, and AI-generated protocol suggestions. All content on this platform is strictly for educational and research purposes.
            </p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-lg text-accent-cyan mb-3">3. Educational Purpose Only</h2>
            <p className="text-text-secondary text-sm leading-relaxed">
              All information provided by Peptidrop, including but not limited to peptide data, dosing references, protocol suggestions, and AI-generated content, is provided solely for educational and informational purposes. Nothing on this platform constitutes medical advice, diagnosis, or treatment recommendations. You should always consult with a qualified healthcare professional before making any health-related decisions.
            </p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-lg text-accent-cyan mb-3">4. User Accounts</h2>
            <p className="text-text-secondary text-sm leading-relaxed">
              You are responsible for safeguarding the password that you use to access the Platform and for any activities or actions under your password. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account. You may not use another person's account without permission.
            </p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-lg text-accent-cyan mb-3">5. Subscriptions & Payments</h2>
            <p className="text-text-secondary text-sm leading-relaxed">
              Some features of Peptidrop require a paid subscription or one-time purchase. Subscription fees are billed in advance on a monthly basis. You may cancel your subscription at any time, and cancellation will take effect at the end of the current billing period. Refunds are provided at our discretion and evaluated on a case-by-case basis. Cryptocurrency payments are processed through third-party providers and are subject to their respective terms.
            </p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-lg text-accent-cyan mb-3">6. AI-Generated Content</h2>
            <p className="text-text-secondary text-sm leading-relaxed">
              Protocols and analyses generated by our AI system are algorithmic outputs based on available research data. They are not reviewed by medical professionals and should not be treated as clinical recommendations. AI outputs may contain errors, and we do not guarantee their accuracy, completeness, or applicability to any individual's circumstances.
            </p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-lg text-accent-cyan mb-3">7. Limitation of Liability</h2>
            <p className="text-text-secondary text-sm leading-relaxed">
              To the fullest extent permitted by applicable law, Peptidrop and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenue, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from your use of the Platform.
            </p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-lg text-accent-cyan mb-3">8. Prohibited Uses</h2>
            <p className="text-text-secondary text-sm leading-relaxed">
              You may not use Peptidrop for any unlawful purpose, to solicit others to perform unlawful acts, to violate any regulations, to infringe on intellectual property rights, to submit false or misleading information, to upload malicious code, to spam or phish other users, or to interfere with the Platform's security features.
            </p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-lg text-accent-cyan mb-3">9. Changes to Terms</h2>
            <p className="text-text-secondary text-sm leading-relaxed">
              We reserve the right to modify or replace these Terms at any time at our sole discretion. Material changes will be communicated with at least 30 days notice. Your continued use of the Platform after changes become effective constitutes acceptance of the revised terms.
            </p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-lg text-accent-cyan mb-3">10. Contact</h2>
            <p className="text-text-secondary text-sm leading-relaxed">
              If you have any questions about these Terms of Service, please contact us at legal@peptidrop.me.
            </p>
          </section>
        </div>
      </div>
      <Footer />
    </main>
  )
}
