// app/disclaimer/page.tsx
import Navigation from '@/components/layout/Navigation'
import Footer from '@/components/layout/Footer'

export default function DisclaimerPage() {
  return (
    <main className="min-h-screen">
      <Navigation />
      <div className="pt-24 sm:pt-28 pb-20 max-w-3xl mx-auto px-4 sm:px-6">
        <h1 className="font-display font-bold text-3xl sm:text-4xl mb-2">Disclaimer</h1>
        <p className="text-text-muted text-sm mb-10">Last updated: March 23, 2026</p>

        <div className="glass-panel p-6 sm:p-8 border-accent-amber/20 mb-10">
          <div className="flex items-start gap-3">
            <span className="text-2xl flex-shrink-0">⚠️</span>
            <p className="text-text-secondary text-sm leading-relaxed">
              <strong className="text-accent-amber">This platform is for educational and research purposes only.</strong> Peptidrop does not provide medical advice, diagnosis, or treatment. All information, including AI-generated protocols, dosing references, and synergy data, is intended for informational use and should never be interpreted as a substitute for professional medical consultation.
            </p>
          </div>
        </div>

        <div className="space-y-8">
          <section>
            <h2 className="font-display font-semibold text-lg text-accent-cyan mb-3">Not Medical Advice</h2>
            <p className="text-text-secondary text-sm leading-relaxed">
              The content provided on Peptidrop, including peptide information, protocol suggestions, dosing references, mechanism descriptions, and AI-generated analyses, is compiled from publicly available research literature and is presented for educational purposes only. This information does not constitute medical advice, and should not be relied upon as a basis for making medical decisions. Always seek the guidance of a qualified healthcare provider with any questions you may have regarding a medical condition, treatment, or medication.
            </p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-lg text-accent-cyan mb-3">AI-Generated Content</h2>
            <p className="text-text-secondary text-sm leading-relaxed">
              Protocols and analyses generated by our AI system are algorithmic outputs. They are not reviewed, approved, or endorsed by medical professionals. AI-generated content may contain inaccuracies, omissions, or errors. The AI does not have access to your full medical history, current medications, allergies, or other critical health information that a healthcare provider would consider. Do not act on AI-generated content without consulting a qualified professional.
            </p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-lg text-accent-cyan mb-3">Dosing Information</h2>
            <p className="text-text-secondary text-sm leading-relaxed">
              All dosing information presented on this platform is drawn from published research literature and is provided strictly as an educational reference. Dosing information is non-prescriptive and should not be used to self-medicate or self-treat. Individual responses to peptides vary significantly based on factors including genetics, health status, age, weight, concurrent medications, and other variables. Only a qualified healthcare professional can determine appropriate dosing for an individual.
            </p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-lg text-accent-cyan mb-3">Research Compounds</h2>
            <p className="text-text-secondary text-sm leading-relaxed">
              Many peptides discussed on this platform are research compounds that have not been approved by the FDA or other regulatory bodies for human use. The regulatory status of peptides varies by jurisdiction. It is your responsibility to understand and comply with the laws and regulations in your jurisdiction regarding the purchase, possession, and use of any compounds discussed on this platform.
            </p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-lg text-accent-cyan mb-3">No Guarantee of Results</h2>
            <p className="text-text-secondary text-sm leading-relaxed">
              Peptidrop makes no guarantees regarding the effectiveness, safety, or outcomes of any peptides, protocols, or stacks discussed or generated on this platform. Individual results vary. Past research findings do not guarantee future results, and in vitro or animal study results may not translate to human outcomes.
            </p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-lg text-accent-cyan mb-3">Assumption of Risk</h2>
            <p className="text-text-secondary text-sm leading-relaxed">
              By using this platform, you acknowledge that you understand the educational nature of the content provided, that you will not use this information as a substitute for professional medical advice, and that Peptidrop, its operators, affiliates, and contributors bear no responsibility for any actions taken based on the information provided on this platform.
            </p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-lg text-accent-cyan mb-3">Contact</h2>
            <p className="text-text-secondary text-sm leading-relaxed">
              If you have questions about this disclaimer, contact us at legal@peptidrop.me.
            </p>
          </section>
        </div>
      </div>
      <Footer />
    </main>
  )
}
